### ISSUE TITLE
Pruebas sobre API REST

### ISSUE THREAD

**Issue by alelevinas** [alelevinas/Jobify_AppServer#13]
Para las pruebas funcionales sobre la API REST implementada se deberá utilizar **python** como lenguaje de scripting.

**Comment by jcostamagna** [comment]
Empiezo a trabajar sobre la plantilla de las pruebas, luego habrá que modelarlas para la interfaz del servidor de la app.

**Comment by jcostamagna** [comment]
Ahi te dejo @alelevinas las pruebas de restAPI. Se hace test para cada método, cualquier cosa me preguntas. Saludos.
